
/* =================================
*
*   Adicione novos desenhos aqui
*
* ==================================
*/

var got = [
    'Verão', 'Westeros', 'Jorah Mormont', 'Verme Cinzento', 'Essos', 'A Donzela', 'A Mãe', 'A Velha', 'Aegon Targaryen', 'Aeron Greyjoy', 'Agulha', 'Alliser Thorne', 'Alto Pardal', 'Alto Septão', 'Arya Stark', 'Asha Greyjoy', 'Aço Valiriano', 'Baixada Das Pulgas', 'Balon Greyjoy', 'Banco De Ferro', 'Barristan Selmy', 'Benjen Stark', 'Blackfyre', 'Braavos', 'Bran Stark', 'Brienne De Tarth', 'Bronn', 'Caminhada Da Vergonha', 'Caminhantes Brancos', 'Casa Arryn', 'Casa Baratheon', 'Casa Greyjoy', 'Casa Lannister', 'Casa Stark', 'Casa Targaryen', 'Casa Tully', 'Casa Tyrell', 'Casa Baelish', 'Casa Dos Imortais', 'Casamento Vermelho', 'Castelo Negro', 'Catelyn Stark', 'Cavaleiro Das Cebolas', 'Cersei Lannister', 'Chá Da Lua', 'Clarabela', 'Cão Felpudo', 'Daario Naharis', 'Daenerys Targaryen', 'Deus Afogado', 'Deus Vermelho', 'Deus De Muitas Faces', 'Deuses Antigos', 'Dolorous Edd', 'Doran Martell', 'Dorne', 'Dothraki', 'Drogon', 'Elia Martell', 'Ellaria Sand', 'Escamagris', 'Estrada Do Rei', 'Euron Greyjoy', 'Fantasma', 'Fogovivo', 'Fortaleza Vermelha', 'Fortaleza De Craster', 'Fé Militante', 'Garralonga', 'Gelo', 'Goiva', 'Guarda Real', 'Harrenhal', 'Hodor', 'Homens Sem Rosto', 'Ilhas De Ferro', 'Imaculados', 'Irmandade Sem Bandeiras', 'Jaime Lannister', 'Jardim De Cima', 'Joffrey Baratheon', 'Jon Arryn', 'Jon Snow', 'Khal Drogo', 'Lady', 'Lamento Da Viúva', 'Lancel Lannister', 'Leite De Papoula', 'Longa Noite', 'Loras Tyrell', 'Lorde Varys', 'Lysa Arryn', 'Mance Rayder', 'Mar Estreito', 'Meera Reed', 'Meereen', 'Meistre Aemon', 'Meistre Luwin', 'Meistre Qyburn', 'Melisandre', 'Mindinho', 'Missandei', 'Muralha', 'Myranda', 'Myrcella Baratheon', 'Ned Stark', 'Ninho Da Águia', 'Nymeria', 'O Guerreiro', 'O Estranho', 'O Ferreiro', 'O Pai', 'Oberyn Martell', 'Olly', 'Osha', 'Patrulha Da Noite', 'Pedra Do Dragão', 'Peixe Negro', 'Podrick Payne', 'Ponta Tempestade', 'Porto Real', 'Portões Da Lua', 'Primeiros Homens', 'Pyat Pree', 'Regicida', 'Rei Louco', 'Rei-para-lá-da-muralha', 'Renly Baratheon', 'Represeiro', 'Rhaegal', 'Rhaegar Targaryen', 'Rickon Stark', 'Robb Stark', 'Robert Baratheon', 'Rochedo Casterly', 'Samwell Tarly', 'Sandor Clegane', 'Sansa Stark', 'Selvagens', 'Senhor Comandante', 'Senhora Coração De Pedra', 'Serpentes De Areia', 'Sete Reinos', 'Shae', 'Shireen Baratheon', 'Sonho Verde', 'Stannis Baratheon', 'Syrio Forel', 'Theon Greyjoy', 'Tommen Baratheon', 'Tormund', 'Torre Da Alegria', 'Tridente', 'Troca-peles', 'Trystane Martell', 'Trystante Martell', 'Tyrion Lannister', 'Tywin Lannister', 'Vaes Dothrak', 'Velha Ama', 'Vidente Verde', 'Vidro De Dragão', 'Viserion', 'Viserys Targaryen', 'Walk Of Shame', 'Winterfell', 'Yara Greyjoy', 'Ygritte', 'Fé Dos Sete', 'Ramsay Bolton', 'Valar Dohaeris', 'Valar Morghulis', 'Vento Cinzento', 'Warg', 'Wun-wun'
];
