
/* =================================
*
*   Adicione novos desenhos aqui
*
* ==================================
*/

var verbos = [
    'ler', 'amar', 'arar', 'cair', 'doer', 'roer', 'sair', 'voar', 'votar', 'abrir', 'adiar', 'andar', 'babar', 'boiar', 'caçar', 'casar', 'cavar', 'coçar', 'curar', 'domar', 'falar', 'frear', 'ligar', 'lutar', 'nadar', 'nevar', 'ouvir', 'pagar', 'pisar', 'podar', 'pular', 'regar', 'rezar', 'rodar', 'rolar', 'secar', 'sujar', 'abafar', 'abanar', 'adoçar', 'adubar', 'ajudar', 'alisar', 'anotar', 'apitar', 'atacar', 'avisar', 'berrar', 'bordar', 'buscar', 'calçar', 'chorar', 'chutar', 'clicar', 'cortar', 'cuidar', 'dançar', 'deitar', 'educar', 'entrar', 'fatiar', 'fechar', 'filmar', 'ganhar', 'gostar', 'imitar', 'inalar', 'jantar', 'lamber', 'lançar', 'malhar', 'molhar', 'multar', 'partir', 'pensar', 'perder', 'pescar', 'piorar', 'piscar', 'pousar', 'saciar', 'salgar', 'sambar', 'semear', 'serrar', 'sobrar', 'soldar', 'sorrir', 'surfar', 'teclar', 'torcer', 'tossir', 'vender', 'vestir', 'viajar', 'abaixar', 'abraçar', 'acolher', 'afastar', 'afundar', 'agachar', 'ajustar', 'alinhar', 'almoçar', 'alongar', 'amarrar', 'amassar', 'apontar', 'aquecer', 'aterrar', 'bajular', 'bocejar', 'brincar', 'buzinar', 'cachear', 'capotar', 'cheirar', 'colorir', 'comprar', 'crescer', 'cutucar', 'deletar', 'demolir', 'digitar', 'dirigir', 'ensinar', 'escovar', 'esmagar', 'estudar', 'estufar', 'evoluir', 'galopar', 'grelhar', 'indagar', 'indicar', 'injetar', 'inundar', 'lanchar', 'lustrar', 'maquiar', 'medicar', 'mostrar', 'murchar', 'plantar', 'prender', 'queimar', 'rebocar', 'recusar', 'separar', 'trancar', 'vacinar', 'vomitar', 'acelerar', 'aparecer', 'arrastar', 'arrepiar', 'asfaltar', 'assistir', 'assustar', 'bagunçar', 'bloquear', 'bronzear', 'caminhar', 'carimbar', 'congelar', 'convidar', 'costurar', 'cultivar', 'debruçar', 'degustar', 'derramar', 'derrubar', 'desafiar', 'descamar', 'desmaiar', 'desmatar', 'destruir', 'discutir', 'encostar', 'enxaguar', 'esconder', 'espantar', 'evaporar', 'guinchar', 'hidratar', 'imaginar', 'imprimir', 'observar', 'ordenhar', 'rastejar', 'refletir', 'reprovar', 'sapatear', 'suspirar', 'temperar', 'terminar', 'tricotar', 'tropeçar', 'ventilar', 'abandonar', 'amarrotar', 'anoitecer', 'apodrecer', 'arborizar', 'assombrar', 'atropelar', 'cochichar', 'comemorar', 'conversar', 'descansar', 'descobrir', 'destelhar', 'divorciar', 'empacotar', 'emprestar', 'idolatrar', 'mergulhar', 'monitorar', 'pesquisar', 'registrar', 'trabalhar', 'bombardear', 'amadurecer', 'desarrumar', 'desconfiar', 'esbravejar', 'hipnotizar', 'lacrimejar', 'ultrapassar', 'desaparecer', 'descongelar', 'enlouquecer', 'entrevistar', 'entristecer', 'entusiasmar', 'inspecionar', 'transportar'
];
